version: '3'

services:
  back:
    build: .
    depends_on:
      - database
    command: npm run start:dev
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@database:${DB_PORT}/${DB_NAME}
    ports:
      - ${PORT}:${PORT}
    working_dir: /app
    volumes:
      - ./back:/app

  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

  front:
    build: .
    depends_on:
      - back
    command: npm run dev -- --host
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - ./front:/app

volumes:
  postgres:

